export const sharedKeywords = [
  'open source',
  'community',
  'technology',
  'software development',
  'collaboration',
  'AI development tools',
  'API development tools',
  'GraphQL tools',
  'REST API tools',
  'Model Context Protocol',
  'MCP Connect',
  'GQLPT',
  'GraphQL Debugger',
  'APIPT',
  'AI debugging tools',
  'protocol debugging',
  'GraphQL query generation',
  'API testing tools',
  'Claude tools',
  'OpenAI development',
  'AI workbench',
  'MCP debugging',
  'GraphQL debugging',
  'API observability',
  'AI tool development',
  'AI integration platform',
  'developer tools',
  'AI assistant tools',
  'browser-based AI tools',
  'visual debugging',
  'TypeScript AI tools',
  'React AI components',
  'GraphQL AI',
  'text to GraphQL',
  'natural language queries',
  'API automation',
  'developer productivity',
  'OpenTelemetry',
  'GraphQL tracing',
  'API monitoring',
  'ethical technology',
  'responsible AI development',
  'sustainable tech',
  'social impact technology',
  'philanthropic technology',
  'tech for good',
  'ethical investing',
  'impact driven development',
  'community-first technology',
  'open source philanthropy',
];

export const baseDescription =
  'Rocket Connect helps build and grow open source communities through technology, education, and collaboration. Creators of MCP Connect, GQLPT, GraphQL Debugger, and APIPT - professional AI-powered API development tools for GraphQL, REST, and Model Context Protocol.';

export const organizationStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'Rocket Connect',
  url: 'https://rconnect.tech',
  description:
    'Open source community platform and creators of AI-powered API development tools: MCP Connect, GQLPT, GraphQL Debugger, and APIPT for professional debugging and development.',
  sameAs: [
    'https://github.com/rocket-connect',
    'https://www.linkedin.com/company/rocketconnect/',
    'https://x.com/rconnect_tech',
    'https://www.youtube.com/@rocket-connect',
    'https://mcp.rconnect.tech',
    'https://gqlpt.dev',
    'https://www.graphql-debugger.com',
    'https://www.apipt.dev',
  ],
  makesOffer: [
    {
      '@type': 'SoftwareApplication',
      name: 'MCP Connect',
      description:
        'Professional Model Context Protocol debugging workbench - browser-based development environment for MCP integrations',
      url: 'https://mcp.rconnect.tech',
      applicationCategory: 'DeveloperApplication',
    },
    {
      '@type': 'SoftwareApplication',
      name: 'GQLPT',
      description:
        'AI-powered GraphQL query generation from natural language - TypeScript-first with OpenAI and Anthropic adapters',
      url: 'https://gqlpt.dev',
      applicationCategory: 'DeveloperApplication',
    },
    {
      '@type': 'SoftwareApplication',
      name: 'GraphQL Debugger',
      description:
        'OpenTelemetry-compliant GraphQL debugging platform for identifying errors, slow queries, and performance issues',
      url: 'https://www.graphql-debugger.com',
      applicationCategory: 'DeveloperApplication',
    },
    {
      '@type': 'SoftwareApplication',
      name: 'APIPT',
      description: 'AI-powered API development and testing platform for REST and GraphQL APIs',
      url: 'https://www.apipt.dev',
      applicationCategory: 'DeveloperApplication',
    },
    {
      '@type': 'Service',
      name: 'Open Source Development',
      description: 'Enterprise open source development and community building services',
    },
    {
      '@type': 'Service',
      name: 'Developer Relations',
      description: 'Community management and developer advocacy services',
    },
    {
      '@type': 'Service',
      name: 'Software Training',
      description: 'Technical training and workshop services for development teams',
    },
  ],
};
